In [25]:
import pandas as pd
import numpy as np

In [6]:
a = np.array([1.00000 , 2, 3])

a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('float64'), 8, 3)

In [7]:
a = a+20

a

array([21., 22., 23.])

In [8]:
scores = np.array([1,2,3,4,5,6,7,8])
print(scores)

[1 2 3 4 5 6 7 8]


In [9]:
scores[3:]

array([4, 5, 6, 7, 8])

In [10]:
scores[:3]

array([1, 2, 3])

In [11]:
scores[3:-1]

array([4, 5, 6, 7])

In [13]:
c = np.array([[1,2,3,4],  [5,6,7,8],   [9,10,11,12],  [13,14,15,16]])

c


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
c[0:2, 2:4]

array([[3, 4],
       [7, 8]])

In [20]:
age = np.array([18,19,20,21,22,23,24])

y = age>20
y

array([False, False, False,  True,  True,  True,  True])

In [21]:
x = age -20
x

array([-2, -1,  0,  1,  2,  3,  4])

In [24]:
age = age[age > 20]
age

array([21, 22, 23, 24])

In [27]:
name_series = pd.Series(['김수안', '김수정', '박동윤', '강이안', '강지안', '박동민'])
age_series = pd.Series([19,23,22,19,16,25])
school_series = pd.Series(['고교', '대학', '대학', '고교', '중학교', '대학원'])

grade_series = pd.Series([4.35, 4.23, 4.25, 4.37, 4.25, 4.5])

print(name_series, age_series, school_series , grade_series)

0    김수안
1    김수정
2    박동윤
3    강이안
4    강지안
5    박동민
dtype: object 0    19
1    23
2    22
3    19
4    16
5    25
dtype: int64 0     고교
1     대학
2     대학
3     고교
4    중학교
5    대학원
dtype: object 0    4.35
1    4.23
2    4.25
3    4.37
4    4.25
5    4.50
dtype: float64


In [34]:
path = 'https://github.com/dknife/ML/raw/main/data/'
file = path+'vehicle_prod.csv'

df = pd.read_csv(file)
print(df)

  Unnamed: 0   2007   2008   2009   2010   2011
0      China   7.71   7.95  11.96  15.84  16.33
1         EU  19.02  17.71  15.00  16.70  17.48
2         US  10.47   8.45   5.58   7.60   8.40
3      Japan  10.87  10.83   7.55   9.09   7.88
4      Korea   4.04   3.78   3.45   4.20   4.62
5     Mexico   2.01   2.05   1.50   2.25   2.54


In [35]:
df=pd.read_csv(file, index_col = 0)

print(df)

         2007   2008   2009   2010   2011
China    7.71   7.95  11.96  15.84  16.33
EU      19.02  17.71  15.00  16.70  17.48
US      10.47   8.45   5.58   7.60   8.40
Japan   10.87  10.83   7.55   9.09   7.88
Korea    4.04   3.78   3.45   4.20   4.62
Mexico   2.01   2.05   1.50   2.25   2.54


In [36]:
path = 'https://github.com/dknife/ML/raw/main/data/'
weather_file = path+'weather.csv'

weather=pd.read_csv(weather_file, index_col = 0, encoding='CP949')
print(weather.head(3))
print('weather 데이터의 shape :', weather.shape)

            평균기온  최대풍속  평균풍속
일시                          
2010-08-01  28.7   8.3   3.4
2010-08-02  25.2   8.7   3.8
2010-08-03  22.1   6.3   2.9
weather 데이터의 shape : (3653, 3)


In [43]:
print(weather.describe())

              평균기온         최대풍속         평균풍속
count  3653.000000  3649.000000  3647.000000
mean     12.942102     7.911099     3.936441
std       8.538507     3.029862     1.888473
min      -9.000000     2.000000     0.200000
25%       5.400000     5.700000     2.500000
50%      13.800000     7.600000     3.600000
75%      20.100000     9.700000     5.000000
max      31.300000    26.000000    14.900000


In [44]:
print('평균 분석 ------------------------------------------')
print(weather.mean())
print('표준편차 분석 --------------------------------------')
print(weather.std())

평균 분석 ------------------------------------------
평균기온    12.942102
최대풍속     7.911099
평균풍속     3.936441
dtype: float64
표준편차 분석 --------------------------------------
평균기온    8.538507
최대풍속    3.029862
평균풍속    1.888473
dtype: float64


In [45]:
weather[['최대풍속', '평균풍속']].max()

최대풍속    26.0
평균풍속    14.9
dtype: float64

In [48]:
missing_data = weather[ weather['평균풍속'].isna() ]
print(missing_data)

            평균기온  최대풍속  평균풍속
일시                          
2012-02-11  -0.7   NaN   NaN
2012-02-12   0.4   NaN   NaN
2012-02-13   4.0   NaN   NaN
2015-03-22  10.1  11.6   NaN
2015-04-01   7.3  12.1   NaN
2019-04-18  15.7  11.7   NaN


In [49]:
weather.fillna(0, inplace = True)
print(weather.loc['2012-02-11'])

평균기온   -0.7
최대풍속    0.0
평균풍속    0.0
Name: 2012-02-11, dtype: float64


In [50]:
weather.fillna(weather['평균풍속'].mean(), inplace = True)
print(weather.loc['2012-02-11'])

평균기온   -0.7
최대풍속    0.0
평균풍속    0.0
Name: 2012-02-11, dtype: float64


In [70]:
path = 'https://github.com/dknife/ML/raw/main/data/'
weather_file2 = path+'weather.csv'

weather2=pd.read_csv(weather_file2, index_col = 1, encoding='CP949')
weather2['month'] = pd.DatetimeIndex(weather2['일시']).month
means = weather2.groupby('month').mean()

print(means)

           최대풍속      평균풍속
month                    
1      8.158065  3.757419
2      8.225357  3.946786
3      8.871935  4.390291
4      9.305017  4.622483
5      8.548710  4.219355
6      6.945667  3.461000
7      7.322581  3.877419
8      6.853226  3.596129
9      6.896333  3.661667
10     7.766774  3.961613
11     8.013333  3.930667
12     8.045484  3.817097
